name: Test

env:
  PASSWORDS: testpassword=${{ secrets.TESTPASSWORD }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install npm packages
        run: yarn ci

      - name: Lint project
        if: always()
        run: yarn lint

      - name: Run UI tests
        if: always()
        run: ${{ env.PASSWORDS }} yarn test-ui-headless
